services:
  database:
    platform: linux/amd64
    image: mysql:5.7
    container_name: db_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=localhost
      - TZ=America/Bogota
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/logs/mysql:/var/log/mysql/
      - ./configs/mysql/conf.d:/etc/mysql/conf.d
      - ./configs/mysql/db:/etc/mysql/db
    ports:
      - 3306:3306
    networks:
      - app-network
  php:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    container_name: php_app
    restart: always
    links:
      - database
    volumes:
      - ./app:/var/www/html
    ports:
      - 8000:8000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
